FROM node:lts-alpine AS base

ARG DISCORD_APP_TOKEN
ARG DISCORD_CLIENT_ID
ARG GITHUB_APP_ID
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GITHUB_INSTALLATION_ID
ARG GITHUB_PRIVATE_KEY
ARG GITHUB_USERNAME_OR_ORG
ARG GITHUB_WEBHOOK_SECRET
ARG TURSO_AUTH_TOKEN
ARG TURSO_URL

ENV DISCORD_APP_TOKEN=${DISCORD_APP_TOKEN}
ENV DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
ENV GITHUB_APP_ID=${GITHUB_APP_ID}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
ENV GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
ENV GITHUB_USERNAME_OR_ORG=${GITHUB_USERNAME_OR_ORG}
ENV GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
ENV TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
ENV TURSO_URL=${TURSO_URL}

WORKDIR /home/node/app

COPY . .

RUN rm -rf ./node_modules

RUN apk add --no-cache py-setuptools python3 make g++
RUN npm install --global corepack@latest
RUN corepack enable pnpm
RUN pnpm install --frozen-lockfile

CMD [ "npm", "start" ]
